// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcuyjobnghfihdcfwfgt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjdXlqb2JuZ2hmaWhkY2Z3Zmd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA0MjQxNTMsImV4cCI6MjA3NjAwMDE1M30.OwCWvMpnQdK2WJHfteYpitMO_WtDxpttF2M5HRiZxRI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});